import{a as b,S as w,i as s}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const S="55210973-f163c09f944895a3800208151",v="https://pixabay.com/api/";async function u(e,t=1){const o={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await b.get(v,{params:o})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more-btn"),h=document.querySelector(".loader-container"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(e){const t=e.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
          <div class="info">
            <p><b>Likes</b> ${o.likes}</p>
            <p><b>Views</b> ${o.views}</p>
            <p><b>Comments</b> ${o.comments}</p>
            <p><b>Downloads</b> ${o.downloads}</p>
          </div>
        </a>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function B(){f.innerHTML=""}function y(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}function M(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}const P=document.querySelector(".form"),$=document.querySelector(".load-more-btn");let i="",a=1;const E=15;P.addEventListener("submit",O);$.addEventListener("click",x);async function O(e){if(e.preventDefault(),i=e.currentTarget.elements["search-text"].value.trim(),a=1,i===""){s.warning({message:"Please enter a search term"});return}B(),d(),y();try{const t=await u(i,a);t.hits.length===0?s.error({message:"Sorry, no images found."}):(p(t.hits),L(t.totalHits))}catch{s.error({message:"Something went wrong!"})}finally{g(),e.target.reset()}}async function x(){a+=1,d(),y();try{const e=await u(i,a);p(e.hits),I(),L(e.totalHits)}catch{s.error({message:"Error loading more images"})}finally{g()}}function L(e){const t=Math.ceil(e/E);a>=t?(d(),e>0&&s.info({message:"We're sorry, but you've reached the end of search results."})):M()}function I(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
