import{a as b,S as w,i as n}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const S="55210973-f163c09f944895a3800208151",v="https://pixabay.com/api/";async function f(e,t=1){const o={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await b.get(v,{params:o})).data}const m=document.querySelector(".gallery");document.querySelector(".load-more-btn");const h=document.querySelector(".loader-container"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(e){const t=e.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
          <div class="info">
            <p><b>Likes</b> ${o.likes}</p>
            <p><b>Views</b> ${o.views}</p>
            <p><b>Comments</b> ${o.comments}</p>
            <p><b>Downloads</b> ${o.downloads}</p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),q.refresh()}function P(){m.innerHTML=""}function y(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}const $=document.querySelector(".form"),a=document.querySelector(".load-more-btn");let c="",i=1;const B=15;$.addEventListener("submit",E);a.addEventListener("click",M);async function E(e){if(e.preventDefault(),c=e.currentTarget.elements["search-text"].value.trim(),i=1,c===""){n.warning({message:"Please enter a search term"});return}P(),a.classList.add("is-hidden"),y();try{const t=await f(c,i);t.hits.length===0?n.error({message:"Sorry, no images found."}):(p(t.hits),L(t.totalHits))}catch{n.error({message:"Something went wrong!"})}finally{g(),e.target.reset()}}async function M(){i+=1,y(),a.classList.add("is-hidden"),u();try{const e=await f(c,i);p(e.hits),u(),L(e.totalHits)}catch{n.error({message:"Error loading more images"})}finally{g()}}function L(e){const t=Math.ceil(e/B);i>=t?(a.classList.add("is-hidden"),e>0&&n.info({message:"We're sorry, but you've reached the end of search results."})):a.classList.remove("is-hidden")}function u(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
